name: Build and Push Docker Image to ACR

on: 
  workflow_dispatch:
    inputs:
      runBuildPush:
        description: 'Run Build and Push'
        required: true
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'
      runDeploy:
        description: 'Run Deploy'
        required: true
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'
      vmIP:
        description: 'Target VM IP'
        required: true
        type: string

  push:
    branches:
      - main
      - 'poc'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.AZURE_ACR_LOGIN_SERVER }}
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}

      - name: Build and Push Docker Image
        id: build-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/nodejs-hi-app:${{ github.sha }}

      - name: Deploy to VM
        if: ${{ github.event.inputs.runDeploy == 'true' }}
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ github.event.inputs.vmIP }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd deployment
            sed -i "s|image:.*|image: ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/nodejs-hi-app:${{ github.sha }}|" hi-deploy.yaml
            kubectl apply -f hi-deploy.yaml
